[package]
name = "mbeval-sys"
version = "0.1.0"
edition = "2024"

[dependencies]
libz-sys = { version = "1.1.22", features = ["static"] }
zstd-sys = "2.0.14"

[build-dependencies]
bindgen = "0.71.1"
cc = "1.2.16"
